'use strict';
const $=id=>document.getElementById(id);
const S={docs:new Map(),assets:[],entries:{},revision:0,csrf:'',view:'home',lang:'ja',change:0,saved:0,saving:null,timer:null,busy:false};
const PAGES=[['home','トップページ','⌂'],['words','ことば','≋'],['about','プロフィール','◯'],['contact','一緒につくる・ご相談','↗'],['press','プレス資料','▤']];
const SITE='content/site.md';
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
function button(text,fn,cls=''){const b=el('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;}
function safeUrl(value){const u=String(value||'').trim();if(u.startsWith('/')&&!u.startsWith('//')||u.startsWith('#'))return u;try{const p=new URL(u);if(['https:','http:','mailto:'].includes(p.protocol))return u;}catch{}return '';}
function escapeHtml(t){return String(t).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function parseMd(text){const m={head:{},headOrder:[],sections:{},secOrder:[],preamble:[]};let key=null,buf=[];for(const line of text.split('\n')){if(line.startsWith('## ')){if(key!==null)m.sections[key]=buf.join('\n').trim();key=line.slice(3).trim();buf=[];if(!m.secOrder.includes(key))m.secOrder.push(key);}else if(key===null){const a=line.match(/^([\w.\-]+):\s?(.*)$/);if(a){m.head[a[1]]=a[2];m.headOrder.push(a[1]);}else if(line.trim())m.preamble.push(line);}else buf.push(line);}if(key!==null)m.sections[key]=buf.join('\n').trim();return m;}
function serializeMd(m){const out=[...m.preamble,''];for(const k of new Set([...m.headOrder,...Object.keys(m.head)])){const v=String(m.head[k]??'').trim();if(v)out.push(`${k}: ${v}`);}out.push('');for(const k of new Set([...m.secOrder,...Object.keys(m.sections)])){const v=String(m.sections[k]??'').trim();if(v)out.push(`## ${k}`,v,'');}return out.join('\n').replace(/\n{3,}/g,'\n\n').trim()+'\n';}
function error(message){$('notice').textContent=message;$('notice').hidden=!message;}
async function api(path,data,raw=false){const opts={credentials:'same-origin',headers:{}};if(data!==undefined){opts.method='POST';opts.headers['X-Editor-CSRF']=S.csrf;if(raw){opts.body=data;opts.headers['Content-Type']=data.type;}else{opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(data);}}const response=await fetch(path,opts);let result;try{result=await response.json();}catch{throw Error('編集画面に接続できません。起動用の画面が開いているか確認してください。');}if(!response.ok)throw Error(result.error||'保存できませんでした。');return result;}
function applyState(data){S.csrf=data.csrf;S.assets=data.assets;S.revision=data.draft.revision;S.entries=data.draft.entries;S.docs.clear();for(const doc of data.documents)S.docs.set(doc.path,{...doc,model:parseMd(doc.text)});for(const [path,entry]of Object.entries(S.entries)){const doc=S.docs.get(path)||{path,sha:entry.base_sha,text:''};doc.model=parseMd(entry.text);S.docs.set(path,doc);}S.change=S.saved=0;status();}
function workDocs(){return [...S.docs.values()].filter(d=>d.path.startsWith('content/works/')).sort((a,b)=>(Number(a.model.head.order)||Number(a.path.split('/').pop().split('_')[0])||999)-(Number(b.model.head.order)||Number(b.path.split('/').pop().split('_')[0])||999));}
function currentDoc(){if(['home','words','about'].includes(S.view))return S.docs.get(SITE);if(S.view==='order')return null;if(S.view.startsWith('content/'))return S.docs.get(S.view);return [...S.docs.values()].find(d=>d.model.head.slug===S.view);}
function route(){const d=currentDoc();if(!d||d.path===SITE)return S.view==='about'?'/#about':S.view==='words'?'/#words':'/';if(d.path.startsWith('content/works/'))return `/works/${d.model.head.id}/`;return `/${d.model.head.slug}/`;}
function status(){const pending=S.change>S.saved;$('save-status').textContent=pending?'下書きを保存中…':Object.keys(S.entries).length?'下書き保存済み':'反映済み';$('apply').disabled=S.busy||!Object.keys(S.entries).length;}
const RESCUE='portfolio-writing-rescue';
function keepRescue(){try{localStorage.setItem(RESCUE,JSON.stringify({entries:S.entries,time:Date.now()}));}catch{}}
function touch(doc){const text=serializeMd(doc.model);if(text===doc.text)delete S.entries[doc.path];else S.entries[doc.path]={base_sha:doc.sha,text};S.change++;keepRescue();status();renderNav();clearTimeout(S.timer);S.timer=setTimeout(()=>flush().catch(()=>{}),650);}
async function flush(){clearTimeout(S.timer);if(S.saving)return S.saving;S.saving=(async()=>{while(S.saved<S.change){const version=S.change;const result=await api('/api/draft',{revision:S.revision,entries:structuredClone(S.entries)});S.revision=result.revision;S.saved=version;}try{localStorage.removeItem(RESCUE);}catch{}error('');status();})().catch(e=>{$('save-status').textContent='保存できていません';error(e.message);throw e;}).finally(()=>{S.saving=null;});return S.saving;}
function navItem(label,glyph,view,doc){const b=button('',()=>openView(view),'nav-item'+(S.view===view?' active':''));b.setAttribute('aria-current',S.view===view?'page':'false');if(doc?.model.head.image){const img=el('img');img.src='/assets/'+doc.model.head.image;img.alt='';b.append(img);}else b.append(el('span','nav-glyph',glyph));b.append(el('span','nav-title',label));if(doc&&S.entries[doc.path])b.append(el('span','dirty-dot'));return b;}
function renderNav(){const nav=$('pages');nav.replaceChildren();for(const [view,title,icon]of PAGES){const doc=['home','words','about'].includes(view)?S.docs.get(SITE):[...S.docs.values()].find(d=>d.model.head.slug===view);if(doc)nav.append(navItem(title,icon,view,doc));}const works=$('works');works.replaceChildren();for(const doc of workDocs())works.append(navItem(doc.model.head.title||'無題の作品','◇',doc.path,doc));$('order-open').classList.toggle('active',S.view==='order');}
function openView(view){S.view=view;renderNav();renderDocument();$('sidebar').classList.remove('open');if(!$('preview-panel').hidden)refreshPreview();window.scrollTo(0,0);}
function plainField(parent,doc,key,label,scope='head'){const field=el('div','field'),input=el('input');const lab=el('label','',label);const id='f-'+key.replace(/\W/g,'-');input.id=id;lab.htmlFor=id;input.value=doc.model[scope][key]||'';input.addEventListener('input',()=>{doc.model[scope][key]=input.value.replace(/[\r\n]/g,' ');touch(doc);});field.append(lab,input);parent.append(field);return input;}
function articleLinks(parent,doc){const entries=(doc.model.sections.links||'').split('\n').filter(l=>l.includes('|')).map(l=>l.split('|').map(s=>s.trim()));const save=()=>{doc.model.sections.links=entries.map(e=>e.join(' | ')).join('\n');touch(doc);};const draw=()=>{parent.querySelectorAll('.article-link-fields,.add-article').forEach(n=>n.remove());entries.forEach((entry,index)=>{const group=el('div','article-link-fields');for(const [i,label]of ['タイトル（日本語）','タイトル（英語）','日付・ひとこと','リンク先'].entries()){const field=el('div','field'),lab=el('label','',label),input=el('input');input.value=entry[i]||'';input.setAttribute('aria-label',label);input.oninput=()=>{entry[i]=input.value.replace(/[|\n]/g,' ');save();};field.append(lab,input);group.append(field);}group.append(button('このリンクを外す',()=>{const previous=doc.model.sections.links;entries.splice(index,1);save();draw();offerUndo('リンクを外しました',()=>{doc.model.sections.links=previous;touch(doc);renderDocument();});}));parent.append(group);});parent.append(button('＋ 記事へのリンク',()=>{entries.push(['','','','']);save();draw();},'add-article'));};draw();}
function languageTabs(parent){const tabs=el('div','language-tabs');for(const [lang,title]of [['ja','日本語'],['en','English']]){const b=button(title,()=>{S.lang=lang;renderDocument();},S.lang===lang?'active':'');b.setAttribute('aria-pressed',String(S.lang===lang));tabs.append(b);}parent.append(tabs);}
// Only simple inline formatting is retained; pasted HTML is never inserted.
function renderInline(text){const holder=el('div');const htmlSource=String(text).replace(/&(?:#[xX][0-9a-fA-F]+|#\d+|[a-zA-Z]+);/g,entity=>{const t=el('textarea');t.innerHTML=entity;return t.value;}).replace(/<a\s+[^>]*href="([^"]+)"[^>]*>(.*?)<\/a>/gi,(_,u,t)=>`[${t}](${u})`);let escaped=escapeHtml(htmlSource);escaped=escaped.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/(?<!\*)\*([^*]+)\*(?!\*)/g,'<em>$1</em>');escaped=escaped.replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>{const decoded=el('textarea');decoded.innerHTML=url;const safe=safeUrl(decoded.value);return safe?`<a href="${escapeHtml(safe)}">${label}</a>`:label;});holder.innerHTML=escaped;return holder.innerHTML;}
function inlineText(node){if(node.nodeType===Node.TEXT_NODE)return escapeHtml(node.nodeValue).replace(/^## /gm,'&#35;&#35; ');if(node.nodeType!==Node.ELEMENT_NODE)return '';const t=node.tagName;let value=[...node.childNodes].map(inlineText).join('');if(t==='BR')return '\n';if(t==='STRONG'||t==='B')return `**${value}**`;if(t==='EM'||t==='I')return `*${value}*`;if(t==='A'){const url=safeUrl(node.getAttribute('href'));return url?`[${value}](${url})`:value;}if(t==='DIV'||t==='P')return '\n'+value;return value;}
function insertTextAtCaret(text){const selection=getSelection();if(!selection.rangeCount)return;const range=selection.getRangeAt(0);range.deleteContents();const node=document.createTextNode(text);range.insertNode(node);range.setStartAfter(node);range.collapse(true);selection.removeAllRanges();selection.addRange(range);}
function editable(node,onInput){node.contentEditable='true';node.spellcheck=false;node.setAttribute('role','textbox');node.setAttribute('aria-multiline','true');node.addEventListener('paste',event=>{event.preventDefault();insertTextAtCaret(event.clipboardData.getData('text/plain'));node.dispatchEvent(new Event('input',{bubbles:true}));});node.addEventListener('drop',event=>event.preventDefault());node.addEventListener('input',onInput);node.addEventListener('click',event=>{if(event.target.closest('a'))event.preventDefault();});}
function parseBlocks(text){if(!text.trim())return [{type:'text',text:''}];return text.split(/\n\s*\n/).map(part=>{if(part.trim()==='{{form}}')return {type:'form',text:part};const image=part.trim().match(/^!\[([^\]]*)\]\(([^)]+)\)$/);if(image)return {type:'image',alt:image[1],url:image[2]};if(part.startsWith('### '))return {type:'heading',text:part.slice(4)};if(part.split('\n').every(line=>line.startsWith('- ')))return {type:'list',text:part.split('\n').map(line=>line.slice(2)).join('\n')};return {type:'text',text:part};});}
function serializeBlocks(blocks){return blocks.map(b=>b.type==='image'?`![${(b.alt||'').replace(/[\[\]]/g,'')}](${b.url})`:b.type==='form'?'{{form}}':b.type==='heading'?`### ${b.text}`:b.type==='list'?b.text.split('\n').map(line=>'- '+line).join('\n'):b.text).filter(t=>t.trim()).join('\n\n');}
let undoAction=null,linkRange=null,linkTarget=null;
function offerUndo(text,action){undoAction=action;$('toast-text').textContent=text;$('toast').hidden=false;}
$('undo').onclick=()=>{if(undoAction)undoAction();$('toast').hidden=true;undoAction=null;};
function formatSelection(target,tag){const selection=getSelection();if(!selection.rangeCount)return;const range=selection.getRangeAt(0);if(!target.contains(range.commonAncestorContainer)||range.collapsed)return;const wrap=document.createElement(tag);wrap.append(range.extractContents());range.insertNode(wrap);range.selectNodeContents(wrap);selection.removeAllRanges();selection.addRange(range);target.dispatchEvent(new Event('input',{bubbles:true}));}
function openLink(target){const selection=getSelection();linkRange=selection.rangeCount&&target.contains(selection.getRangeAt(0).commonAncestorContainer)?selection.getRangeAt(0).cloneRange():null;linkTarget=target;$('link-text').value=linkRange?.toString()||'';$('link-url').value='';$('link-dialog').showModal();$('link-text').focus();}
$('link-cancel').onclick=()=>$('link-dialog').close();
$('link-form').onsubmit=event=>{event.preventDefault();const url=safeUrl($('link-url').value);if(!url){$('link-url').setCustomValidity('https:// で始まるURLを入力してください。');$('link-url').reportValidity();return;}$('link-url').setCustomValidity('');const a=el('a','',$('link-text').value);a.href=url;if(linkRange){linkRange.deleteContents();linkRange.insertNode(a);}else linkTarget.append(a);linkTarget.dispatchEvent(new Event('input',{bubbles:true}));$('link-dialog').close();};
$('link-url').oninput=()=>$('link-url').setCustomValidity('');
function section(parent,doc,key,label,rich=true){const box=el('section','section'),heading=el('div','section-label');heading.append(el('span','',label));box.append(heading);const area=el('div');box.append(area);let blocks=parseBlocks(doc.model.sections[key]||'');const persist=()=>{doc.model.sections[key]=serializeBlocks(blocks);touch(doc);};
 const render=()=>{area.replaceChildren();blocks.forEach((block,index)=>{const item=el('div','block '+block.type),tools=el('div','block-tools');let editor;
 if(block.type==='form'){item.append(el('div','', '連絡先の案内がここに表示されます。'));area.append(item);return;}
 const move=delta=>{const j=index+delta;if(j<0||j>=blocks.length)return;[blocks[index],blocks[j]]=[blocks[j],blocks[index]];persist();render();};
 tools.append(button('↑',()=>move(-1)),button('↓',()=>move(1)));tools.children[0].setAttribute('aria-label','このブロックを上へ');tools.children[1].setAttribute('aria-label','このブロックを下へ');
 if(block.type!=='image'){
  if(rich===true){const select=el('select');select.setAttribute('aria-label','ブロックの種類');for(const [value,title]of [['text','本文'],['heading','見出し'],['list','箇条書き']]){const op=el('option','',title);op.value=value;select.append(op);}select.value=block.type;select.onchange=()=>{block.type=select.value;persist();render();};tools.append(select);}
  editor=el('div','block-editor');editor.innerHTML=renderInline(block.text);editor.dataset.placeholder='ここに書く…';editor.setAttribute('aria-label',label+' '+(index+1));editable(editor,()=>{block.text=[...editor.childNodes].map(inlineText).join('').replace(/^\n/,'');persist();});
  if(rich){for(const [title,tag]of [['太字','strong'],['斜体','em']]){const b=button(title,()=>formatSelection(editor,tag));b.onmousedown=e=>e.preventDefault();tools.append(b);}const link=button('リンク',()=>openLink(editor));link.onmousedown=e=>e.preventDefault();tools.append(link);}
 }else{editor=el('figure');const img=el('img');img.src=safeUrl(block.url);img.alt=block.alt||'';const caption=el('input');caption.value=block.alt||'';caption.placeholder='写真の説明';caption.setAttribute('aria-label','写真の説明');caption.oninput=()=>{block.alt=caption.value;img.alt=block.alt;persist();};editor.append(img,caption);tools.append(button('写真を変更',()=>chooseMedia(false,asset=>{block.url=asset.url;persist();render();})));}
 tools.append(button('削除',()=>{const previous=doc.model.sections[key]||'';blocks.splice(index,1);if(!blocks.length)blocks.push({type:'text',text:''});persist();render();offerUndo('ブロックを削除しました',()=>{doc.model.sections[key]=previous;touch(doc);renderDocument();});},'delete-block'));
 item.append(tools,editor);area.append(item);
 });const add=el('div');add.append(button('＋ 文章を追加',()=>{blocks.push({type:'text',text:''});persist();render();area.querySelectorAll('.block-editor')[area.querySelectorAll('.block-editor').length-1]?.focus();},'add-block'));if(rich===true)add.append(button('　＋ 写真',()=>chooseMedia(false,asset=>{blocks.push({type:'image',url:asset.url,alt:''});persist();render();}),'add-block'));area.append(add);
 };render();parent.append(box);}
let mediaCallback=null,mediaVideo=false;
function chooseMedia(video,callback){mediaVideo=video;mediaCallback=callback;renderMedia();$('upload').accept=video?'video/mp4':'image/jpeg,image/png,image/webp,image/gif';$('media-dialog').showModal();}
function renderMedia(){const grid=$('media-grid');grid.replaceChildren();for(const asset of S.assets.filter(a=>a.video===mediaVideo)){const b=button('',()=>{mediaCallback(asset);$('media-dialog').close();},'media-choice');if(asset.video)b.append(el('div','video-tile','▷'));else{const img=el('img');img.src=asset.url;img.alt=asset.name;img.loading='lazy';b.append(img);}b.append(el('span','',asset.name));grid.append(b);}if(!grid.children.length)grid.append(el('p','quiet','ファイルを追加すると、ここに表示されます。'));}
$('media-close').onclick=()=>$('media-dialog').close();
$('upload').onchange=async()=>{const file=$('upload').files[0];if(!file)return;if(file.size>32*1024*1024){error('ファイルは32MB以内にしてください。');return;}$('upload').disabled=true;try{const asset=await api('/api/upload',file,true);S.assets.push(asset);mediaCallback(asset);$('media-dialog').close();error('');}catch(e){error(e.message);}finally{$('upload').disabled=false;$('upload').value='';}};
function cover(parent,doc,key='image'){const box=el('div','cover');const name=doc.model.head[key];if(name){const img=el('img');img.src='/assets/'+name;img.alt='表紙';box.append(img);}else box.append(el('span','quiet','表紙の写真を選んでください'));const actions=el('div','cover-actions');actions.append(button(name?'写真を変更':'＋ 写真を追加',()=>chooseMedia(false,asset=>{doc.model.head[key]=asset.name;if(key==='image')doc.model.head.card='yes';touch(doc);renderDocument();})));box.append(actions);parent.append(box);}
function gallery(parent,doc){const field=el('section','section');field.append(el('div','section-label','追加の写真'));const row=el('div','media-row');const names=(doc.model.head.gallery||'').split(',').map(s=>s.trim()).filter(Boolean);for(const [i,name]of names.entries()){const card=el('div','media-card'),img=el('img');img.src='/assets/'+name;img.alt='追加写真 '+(i+1);card.append(img,button('×',()=>{const previous=doc.model.head.gallery;names.splice(i,1);doc.model.head.gallery=names.join(', ');touch(doc);renderDocument();offerUndo('写真をページから外しました',()=>{doc.model.head.gallery=previous;touch(doc);renderDocument();});}));card.querySelector('button').setAttribute('aria-label','この写真をページから外す');row.append(card);}row.append(button('＋ 写真を追加',()=>chooseMedia(false,asset=>{names.push(asset.name);doc.model.head.gallery=names.join(', ');touch(doc);renderDocument();}),'media-add'));field.append(row);parent.append(field);}
function title(parent,doc,key,value,scope='head'){const h=el('h1','',value||'');if(key){h.dataset.placeholder='タイトル';editable(h,()=>{doc.model[scope][key]=h.innerText.replace(/[\r\n<>]/g,'').trim();touch(doc);});h.setAttribute('aria-label','タイトル');h.setAttribute('aria-multiline','false');h.addEventListener('keydown',e=>{if(e.key==='Enter')e.preventDefault();});}parent.append(h);return h;}
function details(parent,label){const d=el('details');d.append(el('summary','',label));parent.append(d);return d;}
function renderDocument(){const main=$('document');main.replaceChildren();if(S.view==='order'){renderOrder(main);return;}const doc=currentDoc();if(!doc){main.append(el('p','empty-state','ページが見つかりません。'));return;}const m=doc.model,L=S.lang;
 $('breadcrumb').textContent=PAGES.find(p=>p[0]===S.view)?.[1]||m.head.title||'作品';main.append(el('p','eyebrow',doc.path.startsWith('content/works/')?'作品 / WORK': 'ページ / PAGE'));
 if(doc.path===SITE){const name=PAGES.find(p=>p[0]===S.view)[1];title(main,null,null,name);main.append(el('p','helper','文章をクリックして書き換えられます。下書きは自動で保存されます。'));languageTabs(main);
  if(S.view==='home'){plainField(main,doc,'hero_name','名前');plainField(main,doc,'hero_role','肩書き');section(main,doc,'intro.'+L,'最初の紹介文',false);section(main,doc,'collaboration.title.'+L,'共同制作の見出し',false);section(main,doc,'collaboration.'+L,'共同制作について',false);const extra=details(main,'名前の下の行');plainField(extra,doc,L==='ja'?'hero_sub_ja':'hero_sub_en','名前の下の行');}
  if(S.view==='words'){plainField(main,doc,'essay.title','エッセイのタイトル','sections');if(L==='ja')section(main,doc,'essay.ja','エッセイ');else section(main,doc,'essay.note.en','英語での紹介',false);plainField(main,doc,'essay.date.'+L,'日付・ひとこと','sections');const extra=details(main,'ほかの記事へのリンク');articleLinks(extra,doc);}
  if(S.view==='home')section(main,doc,'current.'+L,'いま続けていること');
  if(S.view==='about'){section(main,doc,'bio.'+L,'プロフィール');section(main,doc,'cred.'+L,'経歴（学歴・展示・発表・選出・メディア）');section(main,doc,'contact.'+L,'ページ末尾の連絡案内',false);}
 }else if(doc.path.startsWith('content/works/')){
  title(main,doc,'title',m.head.title);main.append(el('p','helper','写真とことばを、少しずつ。書きかけのまま閉じても下書きは残ります。'));cover(main,doc);const row=el('div','field-row');plainField(row,doc,'year','制作年');plainField(row,doc,'year_detail','制作時期・期間');main.append(row);languageTabs(main);section(main,doc,'desc.'+L,'作品をひとことで',false);section(main,doc,'detail.'+L,'作品について');section(main,doc,'process.'+L,'制作の背景');gallery(main,doc);section(main,doc,'gallery_caption.'+L,'写真の説明',false);
  const media=details(main,'映像');plainField(media,doc,'video','YouTube / Vimeo のリンク');const local=el('div','field');local.append(el('label','',m.head.video_file?'サイト内の映像を設定済み':'サイト内の映像'));local.append(button(m.head.video_file?'映像を変更':'＋ 映像を追加',()=>chooseMedia(true,asset=>{m.head.video_file=asset.name;touch(doc);renderDocument();})));if(m.head.video_file)local.append(button('ページから外す',()=>{const prev=m.head.video_file;delete m.head.video_file;touch(doc);renderDocument();offerUndo('映像をページから外しました',()=>{m.head.video_file=prev;touch(doc);renderDocument();});}));media.append(local);cover(media,doc,'video_poster');section(media,doc,'video_caption.'+L,'映像の説明',false);
  const extra=details(main,'クレジット・補足');section(extra,doc,'fact.'+L,'技法・担当・共作者',false);section(extra,doc,'note.'+L,'補足・関連リンク','inline');plainField(extra,doc,'docs','資料へのリンク');section(extra,doc,'concept.'+L,'保存してあるコンセプト文',false);
 }else{
  title(main,doc,'title_'+L,m.head['title_'+L]||m.head.title_ja);main.append(el('p','helper','見出しや文章を、ブロックごとに編集できます。'));languageTabs(main);const aliases={intro:'はじめに',practice:'制作について',terms:'掲載・画像のご利用について',form:'連絡先',possibilities:'一緒にできること',approach:'進め方',bio:'プロフィール',portrait:'ポートレート',images:'作品画像',cv:'経歴',usage:'ご利用について'};const bases=[...new Set(m.secOrder.map(k=>k.replace(/\.(ja|en)$/,'')))];for(const base of bases)section(main,doc,base+'.'+L,aliases[base]||base);const extra=details(main,'ページの説明・表示設定');plainField(extra,doc,'desc_'+L,'ページの短い説明');const label=el('label','quiet'),checkbox=el('input');checkbox.type='checkbox';checkbox.checked=['yes','true','1'].includes(m.head.draft);checkbox.onchange=()=>{m.head.draft=checkbox.checked?'yes':'no';touch(doc);};label.append(checkbox,document.createTextNode(' サイトの一覧に出さない（URLからは見られます）'));extra.append(label);
 }
}
function commitOrder(docs){docs.forEach((doc,index)=>{doc.model.head.order=String((index+1)*10);touch(doc);});const featured=docs.filter(d=>d.model.head.featured);featured.forEach((doc,i)=>{doc.model.head.featured=String(i+1);touch(doc);});renderDocument();}
function renderOrder(main){$('breadcrumb').textContent='作品の並び順';main.append(el('p','eyebrow','作品 / WORKS'));title(main,null,null,'作品の並び順');main.append(el('p','helper','行をドラッグするか、矢印で並べ替えられます。★を付けた3作品までがトップに大きく表示されます。'));const docs=workDocs();let dragged=-1;
 docs.forEach((doc,index)=>{const row=el('div','order-row');row.draggable=true;row.addEventListener('dragstart',e=>{dragged=index;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(index));});row.addEventListener('dragover',e=>{e.preventDefault();row.classList.add('drag-over');});row.addEventListener('dragleave',()=>row.classList.remove('drag-over'));row.addEventListener('drop',e=>{e.preventDefault();row.classList.remove('drag-over');if(dragged<0||dragged===index)return;const [item]=docs.splice(dragged,1);docs.splice(index,0,item);commitOrder(docs);});row.append(el('span','drag-grip','⠿'));if(doc.model.head.image){const img=el('img');img.src='/assets/'+doc.model.head.image;img.alt='';row.append(img);}row.append(el('span','order-title',doc.model.head.title||'無題の作品'));const controls=el('div','order-controls');const move=delta=>{if(index+delta<0||index+delta>=docs.length)return;[docs[index],docs[index+delta]]=[docs[index+delta],docs[index]];commitOrder(docs);};controls.append(button('↑',()=>move(-1)),button('↓',()=>move(1)));controls.children[0].disabled=index===0;controls.children[1].disabled=index===docs.length-1;controls.children[0].setAttribute('aria-label',doc.model.head.title+'を上へ');controls.children[1].setAttribute('aria-label',doc.model.head.title+'を下へ');controls.append(button(doc.model.head.featured?'★ トップ':'☆ トップ',()=>{if(doc.model.head.featured)delete doc.model.head.featured;else{if(!doc.model.head.image){error('トップに載せる作品には、先に表紙の写真を追加してください。');return;}if(docs.filter(d=>d.model.head.featured).length>=3){error('トップは3作品までです。入れ替える作品の★を外してから選んでください。');return;}doc.model.head.featured='99';}error('');touch(doc);commitOrder(docs);},'featured'+(doc.model.head.featured?' on':'')));row.append(controls);main.append(row);});
}
function refreshPreview(){const path=route();const url=new URL(path,location.origin);url.searchParams.set('v',Date.now());$('preview-frame').src=url.href;$('preview-link').href=path;}
$('preview-toggle').onclick=()=>{const p=$('preview-panel');p.hidden=!p.hidden;$('preview-toggle').textContent=p.hidden?'見え方':'閉じる';if(!p.hidden)refreshPreview();};
$('menu').onclick=()=>$('sidebar').classList.toggle('open');$('order-open').onclick=()=>openView('order');
$('new-work').onclick=()=>{const id='work-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+crypto.randomUUID().slice(0,6),path='content/works/'+id+'.md';const text=`id: ${id}\ntitle: 無題の作品\ncard: row\nyear: ${new Date().getFullYear()}\norder: ${(workDocs().length+1)*10}\n\n## desc.ja\n\n## detail.ja\n`;const doc={path,sha:null,text:'',model:parseMd(text)};S.docs.set(path,doc);touch(doc);openView(path);const h=$('document').querySelector('h1');h.focus();const range=document.createRange();range.selectNodeContents(h);const sel=getSelection();sel.removeAllRanges();sel.addRange(range);};
$('apply').onclick=async()=>{if(S.busy)return;S.busy=true;status();$('document').inert=true;$('sidebar').inert=true;$('apply').textContent='反映しています…';try{await flush();await api('/api/apply',{revision:S.revision});const data=await api('/api/state');applyState(data);renderNav();renderDocument();error('');$('preview-panel').hidden=false;$('preview-toggle').textContent='閉じる';refreshPreview();}catch(e){error(e.message);}finally{S.busy=false;$('document').inert=false;$('sidebar').inert=false;$('apply').textContent='プレビューに反映';status();}};
window.addEventListener('beforeunload',e=>{if(S.change>S.saved||S.busy){e.preventDefault();e.returnValue='';}});
api('/api/state').then(data=>{applyState(data);renderNav();renderDocument();let rescue;try{rescue=JSON.parse(localStorage.getItem(RESCUE)||'null');}catch{}if(rescue&&Object.keys(rescue.entries||{}).length){error('前回、保存が完了しなかった書きかけがあります。');const b=button('書きかけを復元',()=>{for(const [path,entry]of Object.entries(rescue.entries)){const doc=S.docs.get(path)||{path,sha:entry.base_sha,text:''};doc.model=parseMd(entry.text);S.docs.set(path,doc);touch(doc);}renderDocument();error('');});$('notice').append(document.createTextNode(' '),b);}}).catch(e=>{error(e.message);$('save-status').textContent='接続できません';$('apply').disabled=true;});
